### ISSUE TITLE
Stopping position

### ISSUE THREAD

**Issue by tazzidhum** [IrwenXYZ/CSA-WSSS-GSX-Profile#5]
![image_2024-08-30_204924549](https://github.com/user-attachments/assets/c57afc86-aad5-49b1-8e94-44d22d58d7af)
![image](https://github.com/user-attachments/assets/329383b2-b803-47b6-8246-01e39ea337fb)

It seems that the stopping position for the 777 is on the first line, where as the actual stopping point should be on the last line. (it makes sense that longer aircrafts stop a bit more forward than shorter aircrafts).

I think this was because you may have followed the text facing the aircraft (refer 2nd pic) instead of the text facing the ground crew (1st pic).

**Comment by IrwenXYZ** [comment]
hellooo thanks for opening an issue, I'll include it in the next update but it might take awhile!

**Comment by IrwenXYZ** [comment]
fixed in 1.5
